#!/usr/bin/env python3
"""Embed the example scenarios into the Swift and Python packages.

Reads scenarios/*.scenario.json and emits two committed, generated files so a
consumer can load a scenario by name with no files on disk (and so a
pip-installed wheel ships the examples):

  Sources/Elmulator/BundledScenarios.swift   enum BundledScenarios { static let all }
  python/src/elmulator/_bundled.py            BUNDLED = {...}

Each value is the scenario's canonical JSON (sorted keys, compact) so the
output is stable. Run with --check in CI to fail when the committed files drift
from scenarios/.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCENARIOS = ROOT / "scenarios"
SWIFT_OUT = ROOT / "Sources" / "Elmulator" / "BundledScenarios.swift"
PY_OUT = ROOT / "python" / "src" / "elmulator" / "_bundled.py"

SUFFIX = ".scenario.json"
NOTICE = "Generated by scripts/build_bundled.py. DO NOT EDIT.\nRegenerate with: python3 scripts/build_bundled.py"


def collect() -> dict:
    out = {}
    for path in sorted(SCENARIOS.glob("*.scenario.json")):
        name = path.name[: -len(SUFFIX)]
        data = json.loads(path.read_text(encoding="utf-8"))
        out[name] = json.dumps(data, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return out


def _swift_literal(text: str) -> str:
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return '"' + escaped + '"'


def render_swift(scenarios: dict) -> str:
    lines = [f"// {NOTICE.splitlines()[0]}", f"// {NOTICE.splitlines()[1]}", "", "enum BundledScenarios {", "    static let all: [String: String] = ["]
    for name in sorted(scenarios):
        lines.append(f"        {json.dumps(name)}: {_swift_literal(scenarios[name])},")
    lines.append("    ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_python(scenarios: dict) -> str:
    lines = [f"# {NOTICE.splitlines()[0]}", f"# {NOTICE.splitlines()[1]}", "", "BUNDLED = {"]
    for name in sorted(scenarios):
        lines.append(f"    {name!r}: {json.dumps(scenarios[name])},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    scenarios = collect()
    if not scenarios:
        print("FAIL: no scenarios found in", SCENARIOS)
        return 1
    outputs = [(SWIFT_OUT, render_swift(scenarios)), (PY_OUT, render_python(scenarios))]

    if "--check" in sys.argv:
        drift = False
        for path, content in outputs:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                print(f"DRIFT: {path.relative_to(ROOT)} is out of date; run python3 scripts/build_bundled.py")
                drift = True
        if not drift:
            print(f"OK: bundled scenarios up to date ({len(scenarios)})")
        return 1 if drift else 0

    for path, content in outputs:
        path.write_text(content, encoding="utf-8")
    print(f"wrote {SWIFT_OUT.relative_to(ROOT)} and {PY_OUT.relative_to(ROOT)} ({len(scenarios)} scenarios)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
